export const landingData = {
  "ai-automation-for-clinics": {
    seoTitle: "AI Automation for Clinics in India",
    eyebrow: "CLINICS + AUTOMATION",
    title: "AI automation for clinics that keeps every enquiry moving.",
    description: "Practical AI automation for clinics in India: respond to enquiries, qualify patients, coordinate appointments, send reminders, and hand off clearly to staff.",
    accent: "violet",
    intro: "Copywrk connects clinic websites, calls, forms, calendars, WhatsApp, and team notifications into a focused patient-enquiry workflow—with clear boundaries and human oversight.",
    audience: "Built for independent clinics, multi-speciality practices, physiotherapy centres, dental clinics, and other appointment-led healthcare businesses.",
    pains: [
      ["Missed enquiries", "Calls and messages arrive while reception is busy or after the clinic has closed."],
      ["Repeated questions", "Staff repeatedly answer location, availability, services, doctor, and appointment questions."],
      ["Manual coordination", "Patient details move between WhatsApp, notebooks, sheets, and calendars without one reliable handoff."],
    ],
    system: [
      ["Capture", "Receive the enquiry from a form, approved message channel, or call workflow."],
      ["Qualify", "Collect only the information the clinic has approved for scheduling and routing."],
      ["Coordinate", "Offer an appropriate next step, appointment window, or human callback."],
      ["Handoff", "Send staff a structured summary with the status and required action."],
    ],
    integrations: "Common connections include clinic websites, Google Calendar, WhatsApp, email, Google Sheets, CRMs, Vapi, Twilio, and n8n. The exact system depends on consent, workflow boundaries, and the tools already in use.",
    exampleTitle: "From evening enquiry to organised morning follow-up.",
    example: "A patient submits an appointment request after closing. The workflow confirms receipt, gathers the approved scheduling details, records a preferred window, and gives reception a concise lead summary when the team returns.",
    faqs: [
      ["Can clinic automation give medical advice?", "It should not. The system is designed for approved administrative tasks such as enquiry handling, qualification, scheduling, reminders, and escalation—not diagnosis or medical decisions."],
      ["Will it work with our existing calendar?", "Often yes. We first review availability rules, staff ownership, and the current scheduling tool before deciding the smallest reliable connection."],
      ["Can staff take over a conversation?", "Yes. Human handoff points should be defined for sensitive, urgent, unusual, or explicitly requested situations."],
    ],
    related: [{href:"/services/receptionist",label:"AI receptionist systems"},{href:"/services/automation",label:"Business automation"}],
  },
  "physiotherapy-clinic-websites": {
    seoTitle: "Physiotherapy Clinic Website Design",
    eyebrow: "PHYSIOTHERAPY + WEB",
    title: "Physiotherapy clinic websites built to earn trust and appointments.",
    description: "Mobile-first physiotherapy clinic website design with clear service pages, local information, appointment journeys, WhatsApp, and follow-up connections.",
    accent: "coral",
    intro: "Copywrk builds clear, credible websites for physiotherapy clinics that explain treatments, introduce practitioners, work properly on phones, and make requesting an appointment simple.",
    audience: "For independent physiotherapists, rehabilitation centres, sports-injury clinics, and multi-location practices that need a stronger digital presence and a cleaner enquiry journey.",
    pains: [
      ["Generic presentation", "Template pages fail to communicate the clinic's specialities, practitioners, treatment approach, and local relevance."],
      ["Mobile friction", "Patients struggle to find services, directions, contact details, or appointment actions on smaller screens."],
      ["Thin service information", "A single services list gives Google and prospective patients little context about what the clinic actually provides."],
    ],
    system: [
      ["Position", "Clarify the clinic's audience, treatment strengths, locations, and most valuable appointment journeys."],
      ["Structure", "Create useful pages for services, practitioners, clinic information, FAQs, and contact options."],
      ["Build", "Design a distinctive responsive experience with fast, accessible navigation."],
      ["Connect", "Link appointment requests to confirmation, qualification, calendar, WhatsApp, or staff follow-up."],
    ],
    integrations: "A physiotherapy website can connect with Google Maps, appointment calendars, WhatsApp, email notifications, analytics, Search Console, forms, and a lightweight lead tracker without forcing the clinic into unnecessary software.",
    exampleTitle: "A patient can understand the clinic before making contact.",
    example: "A visitor lands on a back-pain service page, sees who provides treatment, understands the clinic's approach and location, checks common questions, then requests an appointment through a short mobile-friendly journey.",
    faqs: [
      ["Can you include individual treatment pages?", "Yes. Useful pages can be created for genuine services such as sports rehabilitation, post-operative rehabilitation, back pain, neurological physiotherapy, or home visits."],
      ["Will the website help local SEO?", "The site can provide the technical and content foundation through clear service and location information, metadata, internal links, structured data, and Search Console. Rankings also depend on competition, reputation, and external signals."],
      ["Can appointment requests go to WhatsApp?", "Yes. We can design a clear WhatsApp entry point or a structured form-and-follow-up flow depending on how the clinic wants staff to receive enquiries."],
    ],
    related: [{href:"/services/websites",label:"Website design and development"},{href:"/ai-automation-for-clinics",label:"AI automation for clinics"}],
  },
  "lead-follow-up-automation": {
    seoTitle: "Lead Follow-Up Automation for Businesses",
    eyebrow: "LEADS + RESPONSE",
    title: "Lead follow-up automation that responds before interest fades.",
    description: "Lead follow-up automation for website forms, ad leads, WhatsApp enquiries, and missed calls—qualify, book, record, and hand off consistently.",
    accent: "lime",
    intro: "Copywrk builds focused follow-up workflows that acknowledge new enquiries, ask the right questions, book the next step, update records, and alert the correct person.",
    audience: "For clinics, gyms, recruiters, real-estate teams, agencies, and service businesses that generate leads but lose momentum through slow replies or inconsistent follow-up.",
    pains: [
      ["Delayed replies", "A lead waits in an inbox, spreadsheet, or notification until a team member notices it."],
      ["No qualification standard", "Sales conversations begin without consistent information about need, location, budget, timing, or fit."],
      ["One-and-done follow-up", "Leads that do not answer immediately are forgotten rather than followed up within approved limits."],
    ],
    system: [
      ["Trigger", "Detect a new form, ad lead, missed call, message, or CRM record."],
      ["Respond", "Send a relevant acknowledgement through an approved channel."],
      ["Qualify", "Collect a short, business-specific set of details and identify exceptions."],
      ["Convert", "Book the next step or route a structured summary to a human owner."],
    ],
    integrations: "Possible connections include website and ad forms, WhatsApp, email, calendars, Google Sheets, CRMs, n8n, and internal notifications. Channel rules, consent, timing, and opt-outs are defined before launch.",
    exampleTitle: "A form submission becomes a prepared sales conversation.",
    example: "A prospect requests information, receives an immediate reply, answers three relevant questions, selects a call window, and reaches the assigned salesperson with the original source and qualification summary attached.",
    faqs: [
      ["How quickly can the workflow respond?", "A connected workflow can usually begin shortly after the lead source creates a usable event, subject to the source platform and messaging channel."],
      ["Can it follow up more than once?", "Yes, but the timing, total attempts, business hours, channel policies, consent, and opt-out behaviour should be explicitly defined."],
      ["Does every lead receive the same questions?", "No. Qualification should be tailored to the business and may branch based on service, location, urgency, budget, or another approved criterion."],
    ],
    related: [{href:"/services/followup",label:"Lead follow-up service"},{href:"/services/automation",label:"Business automation"}],
  },
  "website-development": {
    seoTitle: "Website Design and Development",
    eyebrow: "WEB + DIGITAL",
    title: "Website development for businesses ready to look credible and convert.",
    description: "Copywrk provides mobile-first website design and development for clinics, professional services, and growing businesses.",
    accent: "blue",
    intro: "Copywrk is an independent digital studio designing and developing distinctive business websites with clear messaging, responsive performance, enquiry journeys, and practical integrations.",
    audience: "For clinics, professional services, local businesses, and growing teams that need more than a generic template or an attractive page that stops at form submitted.",
    pains: [
      ["Outdated first impression", "The website no longer reflects the quality, focus, or credibility of the real business."],
      ["Unclear conversion path", "Visitors read the page but cannot tell whether to call, enquire, book, visit, or message."],
      ["Disconnected operations", "The website collects interest without connecting it to acknowledgement, tracking, booking, or follow-up."],
    ],
    system: [
      ["Discover", "Understand the offer, audience, competitors, current friction, and desired customer action."],
      ["Message", "Build a page structure and copy hierarchy that makes the business easy to understand."],
      ["Design", "Create a responsive visual system that feels distinctive without sacrificing clarity."],
      ["Launch", "Connect the required forms, analytics, search setup, notifications, and follow-up path."],
    ],
    integrations: "Depending on the project, we connect websites with WhatsApp, Google Calendar, Google Maps, analytics, Search Console, Formspree, email, CRMs, spreadsheets, and follow-up automation.",
    exampleTitle: "A service business gets a website with a next step.",
    example: "Instead of a brochure-style homepage, visitors see the offer, service fit, process, trust information, and one clear action. Every enquiry is acknowledged and reaches the business in a format the team can use.",
    faqs: [
      ["Can you work with businesses remotely?", "Yes. Copywrk can work remotely with businesses in India and internationally."],
      ["Do you build multi-page websites?", "Yes. The structure depends on what customers need to understand and what topics deserve dedicated pages, such as services, locations, practitioners, case studies, or legal information."],
      ["Is SEO included?", "Projects can include crawlable pages, metadata, sitemap and robots configuration, Search Console setup, internal linking, structured data, and search-focused content structure. Competitive ranking remains an ongoing process."],
    ],
    related: [{href:"/services/websites",label:"Website design and development"},{href:"/physiotherapy-clinic-websites",label:"Physiotherapy clinic websites"}],
  },
} as const;

export type LandingKey = keyof typeof landingData;
