export const serviceData = {
  websites: {
    number: "01",
    eyebrow: "DESIGN + DEVELOPMENT",
    seoTitle: "Website Design and Development",
    title: "Websites that turn attention into action.",
    intro: "Distinctive, mobile-first business websites built around your offer, your customers, and one clear next step.",
    color: "coral",
    outcome: "A credible digital presence that makes it easy to understand, trust, and contact your business.",
    audience: "For clinics, physiotherapists, professional services, local businesses, and growing teams whose current website is outdated, unclear, slow on phones, or difficult to update.",
    problems: [
      ["Unclear positioning", "Visitors cannot quickly tell what the business offers, who it helps, or why they should choose it."],
      ["Weak mobile journeys", "Important information and calls to action become difficult to use on the device customers use most."],
      ["Dead-end enquiries", "Forms collect details but do not trigger a fast reply, booking step, or organised team handoff."],
    ],
    features: [
      ["Positioning", "Clarify what you sell, who it is for, and why it matters."],
      ["Responsive design", "A polished experience across phones, tablets, and desktops."],
      ["Conversion paths", "Focused calls to action, enquiry forms, booking, and WhatsApp entry points."],
      ["Connected systems", "Link the website to calendars, inboxes, CRMs, analytics, and follow-up."],
    ],
    steps: ["Understand the business and audience", "Shape the message and page structure", "Design and build the responsive site", "Connect, test, launch, and refine"],
    integrations: ["Google Calendar", "WhatsApp", "Formspree", "Google Analytics", "Search Console", "CRMs and spreadsheets"],
    example: {
      title: "A clinic website that continues after submit.",
      copy: "A patient chooses a service, requests an appointment, receives an immediate confirmation, selects a preferred time, and reaches the clinic team as a structured lead instead of an unlabelled form notification.",
    },
    faqs: [
      ["Can you redesign an existing website?", "Yes. We can preserve useful content and brand elements while rebuilding the structure, mobile experience, messaging, and conversion path."],
      ["Will the website work well on phones?", "Yes. Mobile behaviour is designed and tested as a primary experience, not treated as a smaller desktop layout."],
      ["Can the website connect to booking or WhatsApp?", "Yes. The useful first version can connect forms, calendars, WhatsApp entry points, email notifications, analytics, and approved follow-up workflows."],
    ],
    related: { href: "/website-development", label: "Website design and development" },
  },
  receptionist: {
    number: "02",
    eyebrow: "VOICE + INTELLIGENCE",
    seoTitle: "AI Receptionist Systems",
    title: "Every call answered. Every opportunity captured.",
    intro: "AI receptionist systems that speak with callers, understand their needs, qualify enquiries, and book the next step.",
    color: "violet",
    outcome: "Consistent call handling during busy hours and after closing, with clear boundaries and a human handoff when needed.",
    audience: "For clinics, gyms, real-estate teams, recruiters, and service businesses that lose enquiries when staff are busy, unavailable, or answering the same routine questions repeatedly.",
    problems: [
      ["Missed calls", "Potential customers move to the next business when nobody answers quickly."],
      ["Repetitive enquiries", "Staff time is consumed by availability, pricing, location, and appointment questions."],
      ["Incomplete handoffs", "Call details reach the team without the context needed to take the next action."],
    ],
    features: [
      ["Available", "Handle approved inbound call types during busy hours and after closing."],
      ["Natural", "Use a clear Hindi-English or English conversation style suited to the business."],
      ["Qualified", "Collect names, requirements, location, timing, and other approved details."],
      ["Connected", "Book appointments, send summaries, and escalate when a human is needed."],
    ],
    steps: ["Map call types and boundaries", "Write the conversation and escalation rules", "Connect calendar and notifications", "Test with real scenarios before launch"],
    integrations: ["Vapi", "Twilio", "Google Calendar", "WhatsApp", "Google Sheets", "CRM notifications"],
    example: {
      title: "An after-hours clinic call becomes a booked enquiry.",
      copy: "The receptionist identifies the caller's need, collects approved details, checks available appointment windows, confirms the next step, and sends the clinic a concise summary for review.",
    },
    faqs: [
      ["Does an AI receptionist replace clinic staff?", "No. It handles approved routine conversations and creates a reliable handoff. Sensitive, unusual, or urgent situations should follow defined escalation rules."],
      ["Can it speak Hindi and English?", "The conversation can be designed for English, Hindi-English, or another supported language style, then tested with realistic callers before launch."],
      ["Can it book appointments?", "Yes, when connected to an approved calendar or scheduling workflow with clear availability and booking rules."],
    ],
    related: { href: "/ai-automation-for-clinics", label: "AI automation for clinics" },
  },
  followup: {
    number: "03",
    eyebrow: "SPEED + SALES",
    seoTitle: "Lead Follow-Up Automation",
    title: "Follow up while the lead is still interested.",
    intro: "Lead follow-up automation that responds quickly, asks useful questions, continues polite follow-up, and books the next sales step.",
    color: "lime",
    outcome: "Fewer enquiries left sitting in inboxes or spreadsheets without a clear owner or next action.",
    audience: "For businesses receiving leads from websites, ads, Instagram, WhatsApp, missed calls, or spreadsheets—especially when response speed and consistent qualification affect conversion.",
    problems: [
      ["Slow first response", "Interest falls while a new enquiry waits for someone to notice and reply."],
      ["Inconsistent qualification", "Different team members collect different details, leaving sales calls underprepared."],
      ["Leads forgotten", "Promising enquiries disappear after one unanswered message because no follow-up rhythm exists."],
    ],
    features: [
      ["Fast", "Start follow-up shortly after a form, missed call, or new enquiry."],
      ["Persistent", "Continue using the timing, channels, and limits your business approves."],
      ["Useful", "Capture intent, requirements, budget, location, and timeline."],
      ["Clear handoff", "Book a call or send a concise summary to the right person."],
    ],
    steps: ["Choose the lead sources", "Define qualification questions", "Set follow-up timing and limits", "Connect booking and team handoff"],
    integrations: ["Website forms", "WhatsApp", "Email", "Google Sheets", "Calendars", "CRMs and ad lead sources"],
    example: {
      title: "A website lead receives a useful reply in seconds.",
      copy: "The system acknowledges the enquiry, asks a short set of relevant questions, offers an available call or appointment, records the answers, and alerts the correct team member.",
    },
    faqs: [
      ["Which lead sources can trigger follow-up?", "Common sources include website forms, ad lead forms, missed calls, spreadsheets, CRM records, and approved inbox or messaging workflows."],
      ["Will it send spam?", "It should not. Timing, message limits, opt-out handling, and channel rules are defined before launch and must follow applicable platform and consent requirements."],
      ["Can a human take over?", "Yes. The workflow can stop automation and notify a team member when a lead is qualified, asks for a person, or reaches a defined exception."],
    ],
    related: { href: "/lead-follow-up-automation", label: "Lead follow-up automation" },
  },
  automation: {
    number: "04",
    eyebrow: "SYSTEMS + OPERATIONS",
    seoTitle: "Business Process Automation",
    title: "Make routine work happen reliably.",
    intro: "Business automation systems that move information, trigger follow-ups, update records, and notify your team.",
    color: "blue",
    outcome: "Less copying, chasing, and remembering—and a clearer record of what happened next.",
    audience: "For small and growing businesses that repeatedly copy information between forms, messages, calendars, sheets, and CRMs or depend on one person remembering every next step.",
    problems: [
      ["Manual data entry", "The same customer or task information is repeatedly copied across disconnected tools."],
      ["Missed handoffs", "Work stalls because the next person is not notified or cannot see the current status."],
      ["Invisible failures", "Teams discover late that a confirmation, reminder, record update, or follow-up never happened."],
    ],
    features: [
      ["Connect", "Link forms, email, WhatsApp, calendars, sheets, and CRMs."],
      ["Route", "Send every enquiry or task to the correct person."],
      ["Notify", "Trigger confirmations, reminders, alerts, and approved sequences."],
      ["Track", "Keep records updated so the team sees the current state."],
    ],
    steps: ["Map the current manual process", "Choose the smallest useful automation", "Connect and test each step", "Monitor failures and improve the flow"],
    integrations: ["n8n", "Google Workspace", "WhatsApp", "Email", "Calendars", "Supabase, sheets, and CRMs"],
    example: {
      title: "One enquiry updates every place that matters.",
      copy: "A new form submission creates a structured record, routes the lead, sends the customer a confirmation, schedules the next task, and alerts the team when human action is required.",
    },
    faqs: [
      ["What should we automate first?", "Start with a repetitive, frequent process where delays or copying create a visible customer, time, or revenue cost."],
      ["Do we need to replace our current tools?", "Often no. A useful first automation usually connects the tools the team already understands before introducing new software."],
      ["What happens if an automation fails?", "Important workflows should include logging, alerts, clear ownership, and a manual recovery path rather than silently assuming every step succeeded."],
    ],
    related: { href: "/ai-automation-for-clinics", label: "AI automation for clinics" },
  },
} as const;

export type ServiceKey = keyof typeof serviceData;
