import type{Metadata}from"next";import {LegalPage} from "../legal-content";
export const metadata:Metadata={title:"Terms of Use",description:"Terms governing the Copywrk website and the basis for website, AI system, and automation project engagements.",alternates:{canonical:"/terms"}};
export default function Terms(){return <LegalPage eyebrow="LEGAL / TERMS" title="Clear terms for working together." intro="These terms govern the Copywrk website. Paid projects are also governed by the proposal or written agreement accepted for that work." blocks={[
{title:"Services and scope",body:"Copywrk provides website, AI-agent, follow-up, automation, integration, and consulting services. Exact deliverables, timeline, revisions, support, and price are defined in a project proposal or agreement, which controls if it conflicts with this page."},
{title:"Payment and third-party costs",body:"Work may require an advance and may pause when invoices are overdue. Unless expressly included, domains, hosting, telephony, messaging, AI usage, premium software, payment fees, and other third-party costs are the client’s responsibility."},
{title:"Client responsibilities",body:"Clients must provide accurate information, timely feedback, authorised content, and necessary access. Clients are responsible for lawful use, notices, consent, recordings, messages, and review of consequential outputs."},
{title:"AI limitations",body:"AI systems can misunderstand, make mistakes, or become unavailable. They are not professional medical, legal, financial, emergency, or safety advice. High-impact decisions require appropriate human oversight."},
{title:"Ownership",body:"Each party retains what it already owned. Unless agreed otherwise, final custom deliverables transfer after full payment. Copywrk retains reusable know-how, methods, templates, libraries, and general components while granting the client the rights needed to use the completed work."},
{title:"Acceptable use and results",body:"Services may not be used for deception, harassment, unlawful surveillance, spam, rights violations, system compromise, or illegal activity. Copywrk does not guarantee rankings, revenue, leads, uninterrupted availability, or a particular business result."},
{title:"Liability and jurisdiction",body:"To the extent permitted by law, Copywrk is not liable for indirect or consequential losses. Aggregate project liability will not exceed fees paid for the affected service unless law requires otherwise. These terms are governed by Indian law, subject to any jurisdiction or dispute process agreed in writing."}
]}/>}
